config/routes.rb
Rails.application.routes.draw do
  root 'teachers#home'

  get 'sessions/login'
  post 'sessions/login'
  get 'sessions/logout'

  resources :teachers
  resources :parents

end

app/models/parent.rb
class Parent < ActiveRecord::Base

  belongs_to :teacher
  validates :teacher_id, presence: true
  validates :name, presence: true
  validates :student_name, presence: true
  validates :email, presence: true

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base

  has_secure_password
  has_many :parents
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController
  before_action :logged_in?
  before_action :set_parent, only: [:show, :edit, :update, :destroy]

  # GET /parents
  # GET /parents.json
  def index
    @parents = Parent.all
  end

  # GET /parents/1
  # GET /parents/1.json
  def show
  end

  # GET /parents/new
  def new
    @parent = Parent.new
  end

  # GET /parents/1/edit
  def edit
  end

  # POST /parents
  # POST /parents.json
  def create
    @parent = Parent.new(parent_params)

    respond_to do |format|
      if @parent.save
        format.html { redirect_to @parent, notice: 'Parent was successfully created.' }
        format.json { render :show, status: :created, location: @parent }
      else
        format.html { render :new }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parents/1
  # PATCH/PUT /parents/1.json
  def update
    respond_to do |format|
      if @parent.update(parent_params)
        format.html { redirect_to @parent, notice: 'Parent was successfully updated.' }
        format.json { render :show, status: :ok, location: @parent }
      else
        format.html { render :edit }
        format.json { render json: @parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parents/1
  # DELETE /parents/1.json
  def destroy
    @parent.destroy
    respond_to do |format|
      format.html { redirect_to parents_url, notice: 'Parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parent
      @parent = Parent.find(params[:id])
      if @parent.teacher_id != session[:teacher_id]
        redirect_to parents_path, notice: 'Access Denied'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parent_params
      params.require(:parent).permit(:teacher_id, :name, :student_name, :email)
    end

    def logged_in?
      Teacher.find_by_id(session[:teacher_id]) ? true : (redirect_to sessions_login_path, notice: "Please Login.")
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    if request.post?
      teacher = Teacher.find_by_email(params[:email])
      if teacher && teacher.authenticate(params[:password])
        session[:teacher_id] = teacher.id
        redirect_to root_path, notice: "Login Successful."
      else
        flash.now[:notice] = "Invalid Login. Please Try Again."
      end
    end
  end

  def logout
    session[:teacher_id] = nil
    redirect_to sessions_login_path, notice: "Logout Successful."
  end

end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :logged_in?
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teacher = Teacher.find_by_id(session[:teacher_id])
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    render :index
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  private

    def logged_in?
      Teacher.find_by_id(session[:teacher_id]) ? true : (redirect_to sessions_login_path, notice: "Please Login.")
    end

    def set_teacher
      @teacher = Teacher.find(params[:id])
      if @teacher.id != session[:teacher_id]
        redirect_to teachers_path, notice: 'Access Denied'
      end
    end

    def teacher_params
      params.require(:teacher).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teacherbook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <% teacher = Teacher.find_by_id(session[:teacher_id])%>
    <%= "Welcome, #{teacher.name}! |" if session[:teacher_id] %>
    <%= link_to "Logout", sessions_logout_path if session[:teacher_id]%>
  <p id="notice"><%= notice %></p>
  <%= yield %>

</body>
</html>

app/views/parents/_form.html.erb
<%= form_for(@parent) do |f| %>
  <% if @parent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parent.errors.count, "error") %> prohibited this parent from being saved:</h2>

      <ul>
      <% @parent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :teacher_id, :value => session[:teacher_id]%>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :student_name %><br>
    <%= f.text_field :student_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/parents/edit.html.erb
<h1>Editing Parent</h1>

<%= render 'form' %>

<%= link_to 'Home', root_path %> |
<%= link_to 'Parents Index', parents_path %>

app/views/parents/index.html.erb
<h1>Parents Index</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Student name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parents.where(teacher_id: session[:teacher_id]).each do |parent| %>
      <tr>
        <td><%= parent.name %></td>
        <td><%= parent.student_name %></td>
        <td><%= parent.email %></td>
        <td><%= link_to 'Show', parent %></td>
        <td><%= link_to 'Edit', edit_parent_path(parent) %></td>
        <td><%= link_to 'Destroy', parent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', root_path %> |
<%= link_to 'New Parent', new_parent_path %>

app/views/parents/new.html.erb
<h1>New Parent</h1>

<%= render 'form' %>

<%= link_to 'Home', root_path %> |
<%= link_to 'Parents Index', parents_path %>

app/views/parents/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @parent.name %>
</p>

<p>
  <strong>Student name:</strong>
  <%= @parent.student_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @parent.email %>
</p>

<%= link_to 'Home', root_path %> |
<%= link_to 'Parents Index', parents_path %> |
<%= link_to 'Edit', edit_parent_path(@parent) %> 

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <%= f.hidden_field :teacher_id, :value => session[:teacher_id]%>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing teacher</h1>

<%= render 'form' %>

<%= link_to 'Cancel', root_path %>

app/views/teachers/home.html.erb
<h1>Teacherbook</h1>

<%= link_to "Parent Index", parents_path %> |
<%= link_to "Edit Personal Info", edit_teacher_path(session[:teacher_id]) %>

app/views/teachers/index.html.erb
<h1><%= @teacher.name %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @teacher.name %></td>
        <td><%= @teacher.email %></td>
        <td><%= link_to 'Edit Personal Info', edit_teacher_path(@teacher) %></td>
      </tr>
  </tbody>
</table>

<br>

<%= link_to 'Home', root_path %> |
<%= link_to 'Parent Index', parents_path %>

app/views/teachers/new.html.erb
<h1>New teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>